on:
  push:
    tags:
    - 'v*'

name: Deploy WPF Demo
permissions:
  contents: write

env:
  PROJECT_PATH: WpfDemo/WpfDemo.csproj
  ISS_PATH: WpfDemo/WpfDemo.iss

jobs:
  build:
    name: Deploy WPF Demo
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DotNet 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore Project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-build

      - name: Compile Installer      
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ${{ env.ISS_PATH }}
          options: /O+

      - name: Rename Setup file
        run: ren WpfDemo/output/setup.exe WpfDemo.${{ github.ref_name }}.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: WpfDemo Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body_path: WpfDemo/changes.txt
          files: WpfDemo/output/WpfDemo.${{ github.ref_name }}.exe
          fail_on_unmatched_files: true

Warning: Unexpected input(s) 'release_name', valid inputs are ['body', 'body_path', 'name', 'tag_name', 'draft', 'prerelease', 'files', 
'fail_on_unmatched_files', 'repository', 'token', 'target_commitish', 'discussion_category_name', 'generate_release_notes', 'append_body', 'make_latest']