name: Deploy WPF Demo

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

env:
  PROJECT_PATH: WpfDemo/WpfDemo.csproj
  ISS_PATH: WpfDemo/WpfDemo.iss

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DotNet 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore Project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-build

      - name Compile .exe Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ${{ ISS_PATH }}
          options: /O+

      - run: cd
      - run: dir *.*