on:
  push:
    tags:
    - 'v*'

name: Deploy WPF Demo
permissions:
  contents: write

env:
  APPLICATION_NAME: WpfDemo
  PROJECT_DIR: WpfDemo
  PROJECT_NAME: WpfDemo
  PROJECT_PATH: ${{ PROJECT_DIR }}/${{ PROJECT_NAME }}.csproj
  ISS_PATH: ${{ PROJECT_DIR }}/${{ PROJECT_NAME }}.iss
  OUTPUT_DIR: ${{ PROJECT_DIR }}/output

jobs:
  build:
    name: Deploy WPF Demo
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DotNet 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore Project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-build

      - name: Compile Installer      
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ${{ env.ISS_PATH }}
          options: /O+

      - name: Rename Setup file
        run: ren ${{ env.OUTPUT_DIR }}/setup.exe ${{ env.APPLICATION_NAME }}.${{ github.ref_name }}.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.APPLICATION_NAME }} Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body_path: ${{ env.PROJECT_DIR }}/changes.txt
          files: ${{ env.OUTPUT_DIR }}/${{ env.APPLICATION_NAME }}.${{ github.ref_name }}.exe
          fail_on_unmatched_files: true
